name: buildmain
on:
  workflow_dispatch:

env:
  TAG_NAME: testtcp1

jobs:
  buildroot:
    name: Firmware
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          # Sigmastar [I6B]
          - ssc335_lite

          # Hisilicon ultimate
          - hi3518ev200_ultimate

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Prepare firmware
        run: |
          echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
          echo CACHE_DATE=$(date +%m) >> ${GITHUB_ENV}

      - name: Setup ccache
        if: github.event_name != 'pull_request'
        uses: actions/cache@v4
        with:
          path: /tmp/ccache
          key: ${{matrix.platform}}-${{env.CACHE_DATE}}

      - name: Restore ccache
        if: github.event_name == 'pull_request'
        uses: actions/cache/restore@v4
        with:
          path: /tmp/ccache
          key: ${{matrix.platform}}-${{env.CACHE_DATE}}

      - name: Build firmware
        run: |
          export GIT_HASH=$(git rev-parse --short ${GITHUB_SHA})
          export GIT_BRANCH=${GITHUB_REF_NAME}
          echo GIT_HASH=${GIT_HASH} >> ${GITHUB_ENV}
          echo GIT_BRANCH=${GIT_BRANCH} >> ${GITHUB_ENV}

          mkdir -p /tmp/ccache
          ln -s /tmp/ccache ${HOME}/.ccache
          make BOARD=${{matrix.platform}}

          TIME=$(date -d @${SECONDS} +%M:%S)
          echo TIME=${TIME} >> ${GITHUB_ENV}

          NORFW=$(find output/images -name openipc*nor* -print -quit || true)
          if [ -e ${NORFW} ]; then
            echo NORFW=${NORFW} >> ${GITHUB_ENV}
          fi

          NANDFW=$(find output/images -name openipc*nand* -print -quit || true)
          if [ -e ${NANDFW} ]; then
            echo NANDFW=${NANDFW} >> ${GITHUB_ENV}
          fi

          UIMAGE=$(find output/images -type f -name 'uImage*' -print -quit || true)
          if [ -n "${UIMAGE}" ] && [ -e "${UIMAGE}" ]; then
            echo UIMAGE=${UIMAGE} >> ${GITHUB_ENV}
          fi

          ROOTFS_SQUASHFS=$(find output/images -type f -name 'rootfs.squashfs*' -print -quit || true)
          if [ -n "${ROOTFS_SQUASHFS}" ] && [ -e "${ROOTFS_SQUASHFS}" ]; then
            echo ROOTFS_SQUASHFS=${ROOTFS_SQUASHFS} >> ${GITHUB_ENV}
          fi

          ROOTFS_UBI=$(find output/images -type f -name 'rootfs.ubi*' -print -quit || true)
          if [ -n "${ROOTFS_UBI}" ] && [ -e "${ROOTFS_UBI}" ]; then
            echo ROOTFS_UBI=${ROOTFS_UBI} >> ${GITHUB_ENV}
          fi

      - name: Upload firmware
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{env.TAG_NAME}}
          files: |
            ${{env.NORFW}}
            ${{env.NANDFW}}
            ${{env.UIMAGE}}
            ${{env.ROOTFS_SQUASHFS}}
            ${{env.ROOTFS_UBI}}

      - name: Upload rootfs and kernel artifacts
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: firmware-files-${{matrix.platform}}
          path: |
            ${{env.NORFW}}
            ${{env.NANDFW}}
            ${{env.UIMAGE}}
            ${{env.ROOTFS_SQUASHFS}}
            ${{env.ROOTFS_UBI}}

      - name: Send binary
        if: github.event_name != 'pull_request' && env.NORFW
        run: |
          TG_MSG="Commit: ${GIT_HASH}\nBranch: ${GIT_BRANCH}\nTag: ${TAG_NAME}\nTime: ${TIME}\n\n"
          TG_ICON="\xE2\x9C\x85 GitHub Actions"
          TG_HEADER=$(echo -e ${TG_MSG}${TG_ICON})
          TG_TOKEN=${{secrets.TELEGRAM_TOKEN_BOT_OPENIPC}}
          TG_CHANNEL=${{secrets.TELEGRAM_CHANNEL_OPENIPC_DEV}}
          HTTP=$(curl -s -o /dev/null -w %{http_code} https://api.telegram.org/bot${TG_TOKEN}/sendDocument -F chat_id=${TG_CHANNEL} -F caption="${TG_HEADER}" -F document=@${NORFW})
          echo Telegram response: ${HTTP}
